@startuml
participant User

User -> Parser : Description of metro lines 
activate Parser

Parser -> "Shortest path algorithm" : Weighted graph
deactivate Parser

activate "Shortest path algorithm"
...
User -> "Shortest path algorithm" : Two stations

"Shortest path algorithm" --> User : Shortest path between these two stations
deactivate "Shortest path algorithm"

@enduml